/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DiscountDTO
 */
export interface DiscountDTO {
    /**
     * Unique identifier of the discount
     * @type {number}
     * @memberof DiscountDTO
     */
    'discountId'?: number;
    /**
     * Type of the discount
     * @type {string}
     * @memberof DiscountDTO
     */
    'discountType': string;
    /**
     * Value of the discount
     * @type {number}
     * @memberof DiscountDTO
     */
    'discountValue': number;
    /**
     * Start date of the discount
     * @type {string}
     * @memberof DiscountDTO
     */
    'startDate': string;
    /**
     * End date of the discount
     * @type {string}
     * @memberof DiscountDTO
     */
    'endDate': string;
}

