/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OptionsOptionVaraitonsResponseDTO
 */
export interface OptionsOptionVaraitonsResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof OptionsOptionVaraitonsResponseDTO
     */
    'categoryId'?: number;
    /**
     * 
     * @type {number}
     * @memberof OptionsOptionVaraitonsResponseDTO
     */
    'optionId'?: number;
    /**
     * 
     * @type {string}
     * @memberof OptionsOptionVaraitonsResponseDTO
     */
    'optionName'?: string;
    /**
     * 
     * @type {string}
     * @memberof OptionsOptionVaraitonsResponseDTO
     */
    'optionVariationName'?: string;
}

