/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductWithOptionsDTO
 */
export interface ProductWithOptionsDTO {
    /**
     * 
     * @type {number}
     * @memberof ProductWithOptionsDTO
     */
    'productId': number;
    /**
     * 
     * @type {string}
     * @memberof ProductWithOptionsDTO
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ProductWithOptionsDTO
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof ProductWithOptionsDTO
     */
    'rating': number;
    /**
     * 
     * @type {number}
     * @memberof ProductWithOptionsDTO
     */
    'ratingCount': number;
    /**
     * 
     * @type {number}
     * @memberof ProductWithOptionsDTO
     */
    'categoryId': number;
    /**
     * 
     * @type {string}
     * @memberof ProductWithOptionsDTO
     */
    'categoryName': string;
    /**
     * 
     * @type {number}
     * @memberof ProductWithOptionsDTO
     */
    'optionId': number;
    /**
     * 
     * @type {string}
     * @memberof ProductWithOptionsDTO
     */
    'optionName': string;
    /**
     * 
     * @type {string}
     * @memberof ProductWithOptionsDTO
     */
    'optionVariationName': string;
    /**
     * Available quantity of the product
     * @type {number}
     * @memberof ProductWithOptionsDTO
     */
    'quantity': number;
    /**
     * Price of the product
     * @type {number}
     * @memberof ProductWithOptionsDTO
     */
    'price': number;
}

