/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RegisterRequestDTOAddress
 */
export interface RegisterRequestDTOAddress {
    /**
     * Street name and number.
     * @type {string}
     * @memberof RegisterRequestDTOAddress
     */
    'street': string;
    /**
     * City name.
     * @type {string}
     * @memberof RegisterRequestDTOAddress
     */
    'city': string;
    /**
     * State or province name.
     * @type {string}
     * @memberof RegisterRequestDTOAddress
     */
    'state': string;
    /**
     * Country name.
     * @type {string}
     * @memberof RegisterRequestDTOAddress
     */
    'country': string;
    /**
     * Postal or ZIP code.
     * @type {string}
     * @memberof RegisterRequestDTOAddress
     */
    'zipCode': string;
}

