/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginRequestDTO
 */
export interface LoginRequestDTO {
    /**
     * Unique user identifier.
     * @type {string}
     * @memberof LoginRequestDTO
     */
    'username': string;
    /**
     * User\'s password.
     * @type {string}
     * @memberof LoginRequestDTO
     */
    'password': string;
}

