/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductDTO } from './product-dto';

/**
 * 
 * @export
 * @interface PaginatedProductResponse
 */
export interface PaginatedProductResponse {
    /**
     * 
     * @type {Array<ProductDTO>}
     * @memberof PaginatedProductResponse
     */
    'content'?: Array<ProductDTO>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductResponse
     */
    'totalPages': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductResponse
     */
    'totalElements': number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductResponse
     */
    'size': number;
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedProductResponse
     */
    'number': number;
}

