/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OptionDTO } from './option-dto';

/**
 * 
 * @export
 * @interface CategoryOptionsOptionVariationsResponseDTO
 */
export interface CategoryOptionsOptionVariationsResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof CategoryOptionsOptionVariationsResponseDTO
     */
    'categoryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryOptionsOptionVariationsResponseDTO
     */
    'categoryName'?: string;
    /**
     * 
     * @type {Array<OptionDTO>}
     * @memberof CategoryOptionsOptionVariationsResponseDTO
     */
    'options'?: Array<OptionDTO>;
}

