/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderDTO
 */
export interface OrderDTO {
    /**
     * 
     * @type {number}
     * @memberof OrderDTO
     */
    'orderId'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    'orderDate': string;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    'orderStatus': string;
    /**
     * 
     * @type {number}
     * @memberof OrderDTO
     */
    'memberId': number;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    'paymentId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    'deliveryId'?: string;
}

