/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductWithOptionsVer2DTO } from './product-with-options-ver2-dto';

/**
 * 
 * @export
 * @interface ProductWithOptionsListVer2ResponseDTO
 */
export interface ProductWithOptionsListVer2ResponseDTO {
    /**
     * 
     * @type {Array<ProductWithOptionsVer2DTO>}
     * @memberof ProductWithOptionsListVer2ResponseDTO
     */
    'products'?: Array<ProductWithOptionsVer2DTO>;
}

