/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AddressDTO } from './address-dto';

/**
 * 
 * @export
 * @interface UserDetailsResponseDTO
 */
export interface UserDetailsResponseDTO {
    /**
     * Username of the user
     * @type {string}
     * @memberof UserDetailsResponseDTO
     */
    'username': string;
    /**
     * Email address of the user
     * @type {string}
     * @memberof UserDetailsResponseDTO
     */
    'email': string;
    /**
     * Full name of the user
     * @type {string}
     * @memberof UserDetailsResponseDTO
     */
    'name': string;
    /**
     * 
     * @type {AddressDTO}
     * @memberof UserDetailsResponseDTO
     */
    'address'?: AddressDTO;
    /**
     * Role of the user
     * @type {string}
     * @memberof UserDetailsResponseDTO
     */
    'role'?: string;
    /**
     * Indicates whether the user account is enabled
     * @type {boolean}
     * @memberof UserDetailsResponseDTO
     */
    'enabled'?: boolean;
    /**
     * The date and time when the user account was created
     * @type {string}
     * @memberof UserDetailsResponseDTO
     */
    'created'?: string;
    /**
     * The date and time when the user account was last updated
     * @type {string}
     * @memberof UserDetailsResponseDTO
     */
    'updated'?: string;
    /**
     * List of authorities granted to the user
     * @type {Array<string>}
     * @memberof UserDetailsResponseDTO
     */
    'authorities'?: Array<string>;
}

