/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AllCategoriesByDepthResponseDTO
 */
export interface AllCategoriesByDepthResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof AllCategoriesByDepthResponseDTO
     */
    'topCategoryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof AllCategoriesByDepthResponseDTO
     */
    'topCategoryName'?: string;
    /**
     * 
     * @type {number}
     * @memberof AllCategoriesByDepthResponseDTO
     */
    'midCategoryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof AllCategoriesByDepthResponseDTO
     */
    'midCategoryName'?: string;
    /**
     * 
     * @type {number}
     * @memberof AllCategoriesByDepthResponseDTO
     */
    'lowCategoryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof AllCategoriesByDepthResponseDTO
     */
    'lowCategoryName'?: string;
}

