/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OptionsOptionVariatonsResponseDTO
 */
export interface OptionsOptionVariatonsResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof OptionsOptionVariatonsResponseDTO
     */
    'categoryId': number;
    /**
     * 
     * @type {number}
     * @memberof OptionsOptionVariatonsResponseDTO
     */
    'optionId': number;
    /**
     * 
     * @type {string}
     * @memberof OptionsOptionVariatonsResponseDTO
     */
    'optionName': string;
    /**
     * 
     * @type {string}
     * @memberof OptionsOptionVariatonsResponseDTO
     */
    'optionVariationName': string;
}

