/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductCreateRequestDTO
 */
export interface ProductCreateRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductCreateRequestDTO
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ProductCreateRequestDTO
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof ProductCreateRequestDTO
     */
    'categoryId': number;
}

