/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProductDTO } from './product-dto';

/**
 * 
 * @export
 * @interface ProductListResponseDTO
 */
export interface ProductListResponseDTO {
    /**
     * 
     * @type {Array<ProductDTO>}
     * @memberof ProductListResponseDTO
     */
    'products'?: Array<ProductDTO>;
}

