/* tslint:disable */
/* eslint-disable */
/**
 * ecommerce API
 * ecommerce API MVP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RegisterRequestDTOAddress } from './register-request-dtoaddress';

/**
 * 
 * @export
 * @interface RegisterRequestDTO
 */
export interface RegisterRequestDTO {
    /**
     * Unique user identifier.
     * @type {string}
     * @memberof RegisterRequestDTO
     */
    'username': string;
    /**
     * Unique email address.
     * @type {string}
     * @memberof RegisterRequestDTO
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDTO
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequestDTO
     */
    'password': string;
    /**
     * 
     * @type {RegisterRequestDTOAddress}
     * @memberof RegisterRequestDTO
     */
    'address': RegisterRequestDTOAddress;
}

